name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_webservice
version: 0.4.0
repository: https://github.com/fluttercommunity/flutter_google_places

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^4.2.3
  google_maps_webservice:
    git: https://github.com/ShehanYjoz/google_maps_webservice.git
  http:
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
